# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bots_admin.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'bots_admin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62ots_admin.proto\x12\nbots_admin\"\x1e\n\x0e\x42otNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\x0bStatusReply\x12\x0e\n\x06status\x18\x01 \x01(\t2\xc9\x01\n\tBotsAdmin\x12=\n\x04Ping\x12\x1a.bots_admin.BotNameRequest\x1a\x17.bots_admin.StatusReply\"\x00\x12>\n\x05Start\x12\x1a.bots_admin.BotNameRequest\x1a\x17.bots_admin.StatusReply\"\x00\x12=\n\x04Stop\x12\x1a.bots_admin.BotNameRequest\x1a\x17.bots_admin.StatusReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bots_admin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOTNAMEREQUEST']._serialized_start=32
  _globals['_BOTNAMEREQUEST']._serialized_end=62
  _globals['_STATUSREPLY']._serialized_start=64
  _globals['_STATUSREPLY']._serialized_end=93
  _globals['_BOTSADMIN']._serialized_start=96
  _globals['_BOTSADMIN']._serialized_end=297
# @@protoc_insertion_point(module_scope)
