"""Create table note

Revision ID: d9ce75cb3c8c
Revises:
Create Date: 2024-01-03 18:40:05.205500

"""
from collections.abc import Sequence
from datetime import datetime as dt

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd9ce75cb3c8c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=25), nullable=False),
                    sa.Column('text', sa.String(length=4000), nullable=False),
                    sa.Column('modified', sa.DateTime(timezone=True), nullable=False,
                              onupdate=dt.utcnow(), default=dt.utcnow()),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    # ### end Alembic commands ###
